version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - django_lesson_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - lesson_static:/data/static/
      - lesson_media:/data/media/

  django:
    image: django_lesson:5
    networks:
      - django_lesson_network
    volumes:
      - lesson_static:/home/djangoStartProject/staticfiles/
      - lesson_media:/home/djangoStartProject/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - django_lesson_network
    volumes:
      - lesson_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  django_lesson_network:

volumes:
  lesson_static:
  lesson_media:
  lesson_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
