version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - django_main_network
    volumes:
      - /home/jhk7767/nginx.conf:/etc/nginx/nginx.conf
      - main_static:/data/static/
      - main_media:/data/media/

  django:
    image: djangomain:4
    networks:
      - django_main_network
    volumes:
      - main_static:/home/djangoStartProject/staticfiles/
      - main_media:/home/djangoStartProject/media/
    secrets:
      - DJANGO_SECRET_KEY

  mariadb:
    image: mariadb:10.5
    networks:
      - django_main_network
    volumes:
      - main_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  django_main_network:

volumes:
  main_static:
  main_media:
  main_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
