version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - django_lesson_network
    volumes:
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
      - lesson_static:/data/static/
      - lesson_media:/data/media/

  django:
    image: django_lesson:4
    networks:
      - django_lesson_network
    volumes:
      - lesson_static:/home/djangoStartProject/staticfiles/
      - lesson_media:/home/djangoStartProject/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - django_lesson_network
    volumes:
      - lesson_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  django_lesson_network:

volumes:
  lesson_static:
  lesson_media:
  lesson_mariadb:
